#!/bin/bash

RPM_FILE_PATH=$1
RPM_SIG_PATH=$2
PUBLIC_KEY=$3
RPM_FILE=$(basename $RPM_FILE_PATH)
RPM_SIG=$(basename $RPM_SIG_PATH)
MODULE_NAME="f5_secure_installer_builder"

CWD=$(pwd)
WK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function log() {
    ts=$(date +'%Y-%m-%d %H:%m:%S,%3N')
    echo "$ts - $MODULE_NAME - $1 - $2"
}

function copy_payload() {
    cp $RPM_FILE_PATH $WK_DIR/payload/$RPM_FILE
    cp $RPM_SIG_PATH $WK_DIR/payload/$RPM_SIG
    if ! [ -z "$PUBLIC_KEY" ]; then
        log "INFO" "embedding public key ${PUBLIC_KEY} for install validation"
        cp $PUBLIC_KEY $WK_DIR/payload/public_key.pem
    fi
}

function clean_payload() {
    rm -rf $WK_DIR/payload/$RPM_FILE
    rm -rf $WK_DIR/payload/$RPM_SIG
    rm -rf $WK_DIR/payload/public_key.pem
    rm -rf $WK_DIR/payload.tar.gz
    rm -rf $WK_DIR/decompress
}

function create_payload_archive() {
    cd $WK_DIR/payload
    tar cf $WK_DIR/payload.tar ./*
}


function create_decompression_script() {
    cd $WK_DIR
    echo "#!/bin/bash" > decompress
    echo "export TMPDIR=\`mktemp -d /tmp/icontrollxfsi.XXXXXX\`" >> decompress
    echo "ARCHIVE=\`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' \$0\`" >> decompress
    echo "tail -n+\$ARCHIVE \$0 | tar xz -C \$TMPDIR" >> decompress
    echo "CDIR=\`pwd\`" >> decompress
    echo "cd \$TMPDIR" >> decompress
    echo "./installer ./${RPM_FILE} ./${RPM_SIG}" >> decompress
    echo "installer_exit_code=\$?" >> decompress
    echo "cd \$CDIR" >> decompress
    echo "rm -rf \$TMPDIR" >> decompress
    echo "exit \$installer_exit_code" >> decompress
    echo "" >> decompress
    echo "__ARCHIVE_BELOW__" >> decompress
}


function build() {
    cd $WK_DIR
    if [ -e "payload.tar" ]; then
        gzip payload.tar
        FSI_FILE_BASE_NAME=$(basename ${RPM_FILE_PATH} .rpm)
        FSI_FILE_DIR=$(dirname ${RPM_FILE_PATH})
        FSI_FILE_PATH="${FSI_FILE_DIR}/${FSI_FILE_BASE_NAME}.fsi"
        if [ -e "payload.tar.gz" ]; then
            cat decompress payload.tar.gz > $FSI_FILE_PATH
            chmod +x $FSI_FILE_PATH
            log "INFO" "${FSI_FILE_PATH} created"
            clean_payload
            cd $CWD
        else
            log "ERROR" "payload.tar.gz does not exist"
            clean_payload
            cd $CWD
            exit 1
        fi
    else
        log "ERROR" "payload.tar does not exist"
        clean_payload
        cd $CWD
        exit 1
    fi
}

function usage() {
	echo "usage:"
    echo "    build rpm_file_path rpm_sig_file_path [public_pem_key_path]"	
}


if [ "$#" -lt "2" ];
    then usage
    exit 1
fi

copy_payload
create_payload_archive
create_decompression_script
build

exit 0
