#!/bin/bash
export TMPDIR=`mktemp -d /tmp/icontrollxfsi.XXXXXX`
ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`
tail -n+$ARCHIVE $0 | tar xz -C $TMPDIR
CDIR=`pwd`
cd $TMPDIR
./installer ./f5-declarative-onboarding-1.5.0-8.noarch.rpm ./f5-declarative-onboarding-1.5.0-8.noarch.rpm.sha512.sig
installer_exit_code=$?
cd $CDIR
rm -rf $TMPDIR
exit $installer_exit_code

__ARCHIVE_BELOW__
