#!/bin/bash

WK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
KEY_FILE='archive.pubkey.20160210.pem'
TMOS_KEY_DIR='/usr/lib/install'

function validate_signature() {
    openssl dgst -sha512 -verify "${TMOS_KEY_DIR}/${KEY_FILE}" -signature $2 $1 > /dev/null
    echo $?
}

function install_package() {
    package_name=$(basename $1)
    mkdir -p "/var/lib/cloud/fsiverified"
    cp "${WK_DIR}/${package_name}" "/var/lib/cloud/fsiverified/${package_name}"
    python "${WK_DIR}/package_installer.py" "${package_name}"
}

for pkg in *.rpm; do
    [ -f "${pkg}" ] && [ -f "${pkg}.sha512.sig" ] || break
    validated=$(validate_signature ${pkg} ${pkg}.sha512.sig)
    if [ $validated -ne 0 ]; then
        exit 1
    else
        install_package $1
    fi
done
